---
title: "Автореферат диссертации"
subtitle: "Шаблон по ГОСТ Р 7.0.11-2011"
author:
  - "Фамилия Имя Отчество"
date: today
lang: ru
synopsis:
  thesis_author: "Фамилия Имя Отчество"
  thesis_author_short: "Фамилия И. О."
  thesis_title: "Название диссертации"
  specialty_line_1: "Специальность 2.3.1 --- Системный анализ, управление и обработка информации"
  specialty_line_2: ""
  thesis_degree: "кандидата технических наук"
  thesis_degree_short: "канд. техн. наук"
  thesis_city: "Москва"
  thesis_year: "2026"
  thesis_in_organization: "Федеральном государственном бюджетном образовательном учреждении высшего образования \"Примерный университет\""
  supervisor_regalia: "доктор технических наук, профессор"
  supervisor_fio: "Иванов Иван Иванович"
  supervisor_two_block: ""
  opponent_1_block: "Петров Пётр Петрович,`rдоктор технических наук, профессор,`rФГБОУ ВО \"Первый университет\",`rзаведующий кафедрой"
  opponent_2_block: "Сидоров Сидор Сидорович,`rкандидат технических наук, доцент,`rФГАОУ ВО \"Второй университет\",`rдоцент кафедры"
  opponent_3_block: ""
  leading_organization_title: "Федеральное государственное бюджетное образовательное учреждение высшего образования \"Ведущая организация\""
  defense_date: "15 июня 2026 г. в 14:00"
  defense_council_number: "Д 123.456.78"
  defense_council_title: "ФГБОУ ВО \"Примерный университет\""
  defense_council_address: "101000, г. Москва, ул. Примерная, д. 1"
  synopsis_library: "ФГБОУ ВО \"Примерный университет\""
  synopsis_date: "01 мая 2026 г"
  defense_council_phone: "+7 (495) 000-00-00"
  defense_secretary_regalia: "д-р техн. наук, профессор"
  defense_secretary_fio: "Кузнецов Константин Константинович"
  print_sign_date: "__.__.2026"
  print_order_number: "123"
  print_shop: "Типография университета"
format:
  docx:
    reference-doc: ../../resources/reference-docs/synopsis/reference.docx
    toc: false
    number-sections: false
bibliography:
  - ../../resources/bibliography/author-works.bib
  - ../../resources/bibliography/references.bib
csl: ../../resources/csl/gost-r-7-0-5-2008-numeric-iaa.csl
---

```{julia}
#| include: false
include(normpath(joinpath(pwd(), "scripts", "julia", "plotting.jl")))
using .QuartoGostPlots
quarto_gost_activate!(:synopsis)
```

<!--
Подсказки по автореферату:
- структура: обложка, общая характеристика работы, основное содержание,
  заключение, список публикаций автора;
- на обложке указывают статус "на правах рукописи", автора, название,
  специальность, искомую степень, место и год;
- на обороте указывают организацию, руководителя, оппонентов,
  ведущую организацию, дату и место защиты, библиотеку, дату рассылки,
  ученого секретаря.
-->

::: {.callout-important}
Шаблон автореферата использует отдельный `reference.docx`, сформированный по
мотивам `ref\Russian-Phd-LaTeX-Dissertation-Template\synopsis.tex`: формат A5,
одинарный интервал, титульный лист, оборот и выходные сведения. Поля обложки и
оборота заполняются из блока `synopsis:` в front matter.
:::

# Общая характеристика работы {.unnumbered}

Кратко изложите:

- актуальность темы;
- степень разработанности;
- цель и задачи;
- научную новизну;
- теоретическую и практическую значимость;
- методологию;
- положения, выносимые на защиту;
- апробацию результатов.

# Основное содержание работы {.unnumbered}

По разделам и главам кратко изложите содержание диссертации.

## Первая глава

Содержит аналитический обзор и постановку задачи.

## Вторая глава

Содержит методы, модели, алгоритмы и вычислительную схему.

## Третья глава

Содержит основные результаты и сопоставление с известными решениями.

# Заключение {.unnumbered}

Сформулируйте итоговые результаты и выводы.

# Основные публикации автора по теме диссертации {.unnumbered}

<!--
Для автоматического формирования списка публикаций автора:
- храните работы автора в отдельном .bib, например
  resources\bibliography\author-works.bib;
- либо процитируйте нужные записи в этом разделе, либо добавьте их в nocite:

nocite:
  - '@author-work-1'
  - '@author-work-2'

Quarto/Pandoc формирует здесь единый список по cited/nocited записям.
Если нужен отдельный список работ автора, не смешивайте его с обычными
ссылками на внешние источники в этом документе.
-->

::: {#refs}
:::
